name: flutter_walkthrough
description: Exploring Serialization and Widgets In Flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.0
  url_launcher: ^5.0.0
  intl: ^0.15.7
  http: ^0.12.0+1
  splashscreen: ^1.2.0
  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^6.3.0
  progress_indicators: ^0.1.2

dev_dependencies:
  build_runner: ^1.1.3
  built_value_generator: ^6.3.0
  
  flutter_test:
    sdk: flutter
  
  

flutter icons:
  image_path_android: "assets/images/icon/custom-icon.png"
  image_path_ios: "assets/images/icon/custom-icon.png"
  android: true 
  ios: true 

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon/
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
          style: normal
